#!/bin/bash -x
cd ~
export http_proxy=$https_proxy
sudo -E apt install -y git
git config --global credential.helper store
if [ -d chp ]; then
  cd chp
  git pull
else
  git clone https://shsamg.visualstudio.com/chp/_git/chp
  cd chp
fi
git checkout testcontroller
bash -x infra/testcontroller/install.sh
